In [3]:
import numpy as np

In [3]:
lst = [1,3,5,7]
np.array(lst)

array([1, 3, 5, 7])

In [42]:
type(lst)

list

In [38]:
lst_mix = [1,3,5,7, "null", True]
np.array(lst_mix)

array(['1', '3', '5', '7', 'null', 'True'], dtype='<U11')

In [5]:
arr = np.array(lst)

In [7]:
type(arr)

numpy.ndarray

In [11]:
lst2 = [1,2,3]
lst3 = [4,5,6]
lst4 = [7,8,9]

In [13]:
np.array([lst2,lst3,lst4])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
two_d_array = np.array([lst2,lst3,lst4])

In [19]:
two_d_array.shape

(3, 3)

## Indexing

In [22]:
print(arr[2])

5


In [24]:
print(two_d_array[2][1])

8


In [28]:
two_d_array[2][1] = 10
print(two_d_array[2][1])
print(two_d_array)

10
[[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]


In [36]:
print(two_d_array[1:])

[[ 4  5  6]
 [ 7 10  9]]


# EDA Point of View

In [51]:
arr = np.array(lst)

In [55]:
arr

array([1, 3, 5, 7])

In [57]:
arr < 4

array([ True,  True, False, False])

In [59]:
arr[arr<4]

array([1, 3])

In [73]:
lst2 = [
    [1,2,3,4,5,16],
    [6,7,8,9,10,17],
    [11,12,13,14,15,18]
        ]
arr1 = np.array(lst2)

In [75]:
arr1.shape

(3, 6)

In [77]:
arr1.reshape(6,3)

array([[ 1,  2,  3],
       [ 4,  5, 16],
       [ 6,  7,  8],
       [ 9, 10, 17],
       [11, 12, 13],
       [14, 15, 18]])

In [79]:
arr1.reshape(2,9)

array([[ 1,  2,  3,  4,  5, 16,  6,  7,  8],
       [ 9, 10, 17, 11, 12, 13, 14, 15, 18]])

## Mechanism to create an array

In [5]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [11]:
np.arange(1,20,2).reshape(2,5)
np.arange(1,21,1).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [15]:
lst = [1,3,5,6]
arr = np.array(lst)

In [17]:
arr * arr

array([ 1,  9, 25, 36])

In [23]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [83]:
np.random.randint(10,50,4)

array([39, 24, 32, 16])

In [85]:
np.random.randn(3,5)

array([[ 0.98081731, -0.86009516,  1.14082763,  0.86173398,  0.19100813],
       [-2.10023626,  0.4115609 , -1.18210663,  0.12609317,  0.51466045],
       [-1.40078441,  0.35817482,  0.4884398 ,  0.69251087,  1.96778727]])

In [87]:
np.random.random_sample((4,7))

array([[0.12658659, 0.66369048, 0.95981928, 0.59745166, 0.65528981,
        0.90627792, 0.70187431],
       [0.73367187, 0.98771637, 0.30511673, 0.83149657, 0.61053225,
        0.65626578, 0.59496073],
       [0.09127589, 0.77881443, 0.63149601, 0.68653041, 0.6857286 ,
        0.601022  , 0.53252055],
       [0.69529902, 0.96928971, 0.18831643, 0.95544734, 0.6711837 ,
        0.93825104, 0.30558856]])